//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
namespace RealEstateWebUI.Areas.admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TblImage")]
    public partial class TblImage
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public decimal ImageSize { get; set; }
        public int ProductID { get; set; }

        public virtual Product Product { get; set; }
    }
}
